version: '3'

services:
  app:
    build:
      context: .
      args:
        dev: 1
    command: /bin/sh /srv/app/bin/app.sh --runserver
    volumes:
      - ./app/:/srv/app
      - ./bin:/srv/bin
      - ./lib:/srv/lib
      - ./teleforma/:/srv/src/teleforma/teleforma
      - ./var/media:/srv/media
      - ./var/backup:/srv/backup
      - ./var/static:/srv/static
    ports:
      - "8000:8000"
    links:
      - postgres
    env_file:
      - env/debug.env

  postgres:
    image: postgres
    env_file:
      - env/debug.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./var/lib/postgresql:/var/lib/postgresql/data:rw
      - ./bin:/srv/bin
      - ./var/backup/:/srv/backup
      - /etc/localtime:/etc/localtime:ro

  memcached:
      image: memcached:alpine
      entrypoint:
          - memcached
          - -m 1024
          - -I 128m
          - -v

volumes:
    app:
    db:
