version: '3'

services:
  app:
    build: .
    command: /bin/sh /srv/app/bin/app.sh --runserver
    volumes:
      - ./app/:/srv/app
      - ./bin:/srv/bin
      - ./lib:/srv/lib
      - ./teleforma/:/srv/src/teleforma/teleforma
      - ./var/media:/srv/media
      - ./var/backup:/srv/backup
      - ./var/static:/srv/static
    ports:
      - "8000:8000"
    links:
      - db
    env_file:
      - env/debug.env

  db:
    image: mariadb
    env_file:
      - env/debug.env
    volumes:
      - ./bin:/srv/bin
      - ./var/lib/mysql/:/var/lib/mysql
      - ./var/log/mysql/:/var/log/mysql
      - ./var/backup/:/srv/backup

  memcached:
      image: memcached:alpine
      entrypoint:
          - memcached
          - -m 1024
          - -I 128m
          - -v

volumes:
    app:
    db:
