data:
  image: debian:wheezy
  volumes:
     - ./data/media/:/srv/media
     - ./data/static/:/srv/static
     - ./data/backup/:/srv/backup
  command: "true"

db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=mysecretpassword
    - MYSQL_DATABASE=teleforma
    - MYSQL_USER=teleforma
    - MYSQL_PASSWORD=admin
  volumes:
    - ./data/var/lib/mysql/:/var/lib/mysql
    - ./data/var/log/mysql/:/var/log/mysql

app:
  build: .
  command: /bin/sh deploy/start_app.sh
  volumes:
    - ./app/:/srv/app
    - ./teleforma/:/srv/src/teleforma
  volumes_from:
    - data
  ports:
    - "8000:8000"
  links:
    - db

nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./app/deploy/nginx-app.conf:/etc/nginx/conf.d/default.conf
    - ./data/var/log/nginx/:/var/log/nginx
  volumes_from:
    - data
  links:
    - app
