version: '2'

services:
  var:
    image: debian:jessie
    volumes:
      - ./var/media/:/srv/media
      - ./var/static/:/srv/static
      - ./var/backup/:/srv/backup
    command: "true"

  db:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=teleforma
      - MYSQL_USER=teleforma
      - MYSQL_PASSWORD=admin
    volumes:
      - ./var/lib/mysql/:/var/lib/mysql

  app:
    build: .
    command: /bin/sh deploy/start_app.sh
    volumes:
      - ./app/:/srv/app
      - ./teleforma/:/srv/lib/teleforma/teleforma
    volumes_from:
      - var
    ports:
      - "8000:8000"
    links:
      - db

  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./app/deploy/nginx-app.conf:/etc/nginx/conf.d/default.conf
      - ./var/log/nginx/:/var/log/nginx
    volumes_from:
      - var
    links:
      - app

volumes:
    var:
    app:
    db:
    web:

