# Generated by Django 3.2.3 on 2021-06-01 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teleforma.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teleforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BBBServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='Url du serveur BBB')),
                ('api_key', models.CharField(max_length=100, verbose_name='API Key')),
            ],
            options={
                'verbose_name': 'BBB server',
                'verbose_name_plural': 'BBB servers',
                'db_table': 'teleforma_bbb_server',
            },
        ),
        migrations.CreateModel(
            name='Webclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', teleforma.fields.DurationField(blank=True, default='00:30:00', verbose_name='Durée de la conférence')),
                ('max_participants', models.IntegerField(blank=True, default=80, null=True, verbose_name='Nombre maxium de participants par créneau')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('status', models.IntegerField(choices=[(2, 'Draft'), (3, 'Public')], default=2, verbose_name='status')),
                ('bbb_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webclass', to='webclass.bbbserver', verbose_name='Serveur BBB')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webclass', to='teleforma.course', verbose_name='course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webclass', to='teleforma.department', verbose_name='department')),
                ('iej', models.ManyToManyField(blank=True, related_name='webclass', to='teleforma.IEJ', verbose_name='iej')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webclass', to='teleforma.period', verbose_name='period')),
            ],
            options={
                'verbose_name': 'webclass',
                'verbose_name_plural': 'webclass',
                'db_table': 'teleforma_webclass',
            },
        ),
        migrations.CreateModel(
            name='WebclassSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Jour du créneau')),
                ('start_hour', models.TimeField(verbose_name='heure du créneau')),
                ('room_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='id de la conférence BBB (généré automatiquement)')),
                ('room_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='password du modérateur (généré automatiquement)')),
                ('participants', models.ManyToManyField(blank=True, related_name='webclass_slot', to=settings.AUTH_USER_MODEL, verbose_name='participants')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webclass_slot', to='teleforma.professor', verbose_name='professor')),
                ('webclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='webclass.webclass')),
            ],
            options={
                'verbose_name': 'webclass slot',
                'db_table': 'teleforma_webclass_slot',
            },
        ),
        migrations.CreateModel(
            name='WebclassRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=255, verbose_name='Enregistrement BBB')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de la conférence')),
                ('bbb_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webclass_records', to='webclass.bbbserver', verbose_name='Serveur BBB')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webclass_records', to='teleforma.course', verbose_name='course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleforma.period', verbose_name='period')),
            ],
            options={
                'verbose_name': 'enregistrement',
                'verbose_name_plural': 'enregistrements',
                'db_table': 'teleforma_webclass_record',
            },
        ),
    ]
