# Generated by Django 3.2.3 on 2021-06-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webclass',
            name='platform_only',
            field=models.BooleanField(default=False, verbose_name='platform only'),
        ),
    ]
