# Generated by Django 3.2.3 on 2021-06-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclass', '0002_webclass_platform_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='webclass',
            name='presentiel',
            field=models.BooleanField(default=True, verbose_name='Autoriser présentiel'),
        ),
        migrations.AlterField(
            model_name='webclass',
            name='platform_only',
            field=models.BooleanField(default=True, verbose_name='Autoriser e-learning'),
        ),
    ]
