# Generated by Django 3.2.3 on 2021-06-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webclass', '0003_auto_20210616_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webclass',
            old_name='platform_only',
            new_name='allow_elearning',
        ),
        migrations.RenameField(
            model_name='webclass',
            old_name='presentiel',
            new_name='allow_presentiel',
        ),
    ]
