# Generated by Django 3.2.3 on 2021-07-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclass', '0004_auto_20210616_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='webclassrecord',
            name='category',
            field=models.CharField(choices=[('WC', 'Webclass'), ('CC', 'Correction de copie')], default='WC', max_length=2, verbose_name='Catégorie'),
        ),
    ]
