# Generated by Django 3.2.3 on 2021-12-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclass', '0004_auto_20210616_1654'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webclass',
            index=models.Index(fields=['status', 'period', 'course'], name='teleforma_w_status_03cc4b_idx'),
        ),
    ]
