# Generated by Django 3.2.3 on 2022-01-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclass', '0005_webclass_teleforma_w_status_03cc4b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='webclassrecord',
            name='category',
            field=models.CharField(choices=[('WC', 'Webclass'), ('CC', 'Correction de copie')], default='WC', max_length=2, verbose_name='Catégorie'),
        ),
    ]
