# Generated by Django 3.2.3 on 2021-06-07 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teleforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='init_password',
            field=models.BooleanField(default=False, verbose_name='Password initialized'),
        ),
        migrations.AlterField(
            model_name='student',
            name='confirmation_sent',
            field=models.BooleanField(default=False, verbose_name='confirmation sent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='subscribed'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('room_name', models.CharField(max_length=255, verbose_name='Salon')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='user')),
            ],
            options={
                'db_table': 'teleforma_chat_messages',
            },
        ),
    ]
