# Generated by Django 3.2.3 on 2021-06-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0004_auto_20210609_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
    ]
