# Generated by Django 3.2.3 on 2021-06-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0005_alter_newsitem_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='conference',
        ),
    ]
