# Generated by Django 3.2.3 on 2021-07-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0006_remove_document_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingserver',
            name='path',
            field=models.CharField(blank=True, max_length=256, verbose_name='path'),
        ),
        migrations.AddField(
            model_name='streamingserver',
            name='protocol',
            field=models.CharField(blank=True, max_length=16, verbose_name='protocol'),
        ),
    ]
