# Generated by Django 3.2.3 on 2021-08-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0008_auto_20210715_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='public_id'),
        ),
    ]
