# Generated by Django 3.2.3 on 2021-09-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0009_alter_conference_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='allow_elearning',
            field=models.BooleanField(default=True, verbose_name='Autoriser e-learning'),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='allow_presentiel',
            field=models.BooleanField(default=True, verbose_name='Autoriser présentiel'),
        ),
    ]
