# Generated by Django 3.2.3 on 2021-09-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0009_alter_conference_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_generated',
            field=models.BooleanField(default=False, verbose_name='échances générées'),
        ),
    ]
