# Generated by Django 3.2.3 on 2021-09-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0010_auto_20210927_1556'),
        ('teleforma', '0010_student_payment_generated'),
    ]

    operations = [
    ]
