# Generated by Django 3.2.3 on 2021-09-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0010_student_payment_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
