# Generated by Django 3.2.3 on 2021-09-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0011_coursetype_order'),
        ('teleforma', '0011_merge_20210929_1024'),
    ]

    operations = [
    ]
