# Generated by Django 3.2.3 on 2021-12-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0014_alter_profile_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['course', 'course_type', 'period', 'streaming', '-date_begin'], name='teleforma_c_course__5d8618_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['course', 'is_published', '-date_added'], name='teleforma_d_course__b0ecc5_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['course', 'course_type', 'period', 'is_published', '-date_modified'], name='teleforma_m_course__19f376_idx'),
        ),
    ]
