# Generated by Django 3.2.3 on 2022-06-20 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teleforma.models.notification


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teleforma', '0016_alter_profile_siret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('url', models.CharField(max_length=255, verbose_name='Url')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('expired', models.DateTimeField(default=teleforma.models.notification.in_one_week, verbose_name="Date d'expiration")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'teleforma_notifications',
            },
        ),
    ]
