# Generated by Django 3.2.3 on 2022-06-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0016_alter_profile_siret'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='date_publish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publishing date'),
        ),
    ]
