# Generated by Django 3.2.3 on 2022-06-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Vu'),
        ),
    ]
