# Generated by Django 3.2.3 on 2022-06-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0017_conference_date_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='notified'),
        ),
    ]
