# Generated by Django 3.2.3 on 2022-06-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0018_conference_notified'),
        ('teleforma', '0018_notification_viewed'),
    ]

    operations = [
    ]
