# Generated by Django 3.2.13 on 2023-01-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0020_chatmessage_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publish', models.DateTimeField(blank=True, null=True, verbose_name='publishing date')),
                ('status', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Private'), (2, 'Draft'), (3, 'Public')], default=2, verbose_name='status')),
                ('notified', models.BooleanField(default=False, verbose_name='notified')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='teleforma.conference', verbose_name='conference')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleforma.period', verbose_name='period')),
            ],
        ),
    ]
