# Generated by Django 3.2.13 on 2022-12-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0020_chatmessage_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='nb_script',
        ),
        migrations.AddField(
            model_name='training',
            name='nb_script',
            field=models.IntegerField(blank=True, default=12, null=True, verbose_name='nombre maximal de copies'),
        ),
    ]
