# Generated by Django 3.2.13 on 2023-01-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0021_conferencepublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='notified_live',
            field=models.BooleanField(default=False, verbose_name='Notification live'),
        ),
    ]
