# Generated by Django 3.2.13 on 2022-12-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0021_auto_20221208_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publish', models.DateTimeField(blank=True, null=True, verbose_name='publishing date')),
                ('status', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Private'), (2, 'Draft'), (3, 'Public')], default=2, verbose_name='status')),
                ('notified', models.BooleanField(default=False, verbose_name='notified')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='teleforma.conference', verbose_name='conference')),
                ('trainings', models.ManyToManyField(related_name='conference_publications', to='teleforma.Training', verbose_name='trainings')),
            ],
        ),
    ]
