# Generated by Django 3.2.13 on 2023-03-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0022_conference_notified_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='source',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='notified_live',
            field=models.BooleanField(default=False, verbose_name='Notifié live'),
        ),
    ]
