# Generated by Django 3.2.13 on 2023-03-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0023_auto_20230316_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='source',
        ),
        migrations.AddField(
            model_name='profile',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='teleforma.origin', verbose_name='origin'),
        ),
    ]
