# Generated by Django 3.2.13 on 2023-06-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleforma', '0025_auto_20230607_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='nb_script_per_session',
            field=models.IntegerField(default=1, verbose_name='nombre maximal de copies par session'),
        ),
    ]
