# -*- coding: utf-8 -*-
#
# Copyright (c) 2015 Guillaume Pellerin <guillaume.pellerin@ircam.fr>

# Manifeste is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# Manifeste is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Manifeste.  If not, see <http://www.gnu.org/licenses/>.

# Authors:
# Guillaume Pellerin <guillaume.pellerin@ircam.fr>

version: '3'

services:
  app:
      command: /bin/sh bin/app.sh --runserver
      env_file:
        - 'env/dev.env'
      ports:
        - "9000:8000"

