version: '3'

services:
  app:
    build:
      context: .
      args:
        dev: 0
    command: /bin/sh /srv/app/wsgi.sh
    restart: unless-stopped
    env_file:
      - env/prod.env
    volumes:
      - /mnt/crfpa-videos:/mnt/crfpa-videos
      - /mnt/crfpa-scripts:/mnt/crfpa-scripts
    ports:
      - "9003:8000"
    networks:
      - teleforma-prod
  
  channels:
    build:
      context: .
      args:
        dev: 0
    command: /bin/sh /srv/app/asgi.sh
    volumes:
      - ./app/:/srv/app
      - ./bin:/srv/bin
      - ./lib:/srv/lib
      - ./teleforma/:/srv/src/teleforma/teleforma
      - ./var/log/app:/var/log/app
    ports:
      - "9004:8000"
    links:
      - postgres
      - redis
    env_file:
      - env/prod.env
    networks:
      - teleforma-prod

  postgres:
    image: postgres:13
    env_file:
      - env/prod.env
    networks:
      - teleforma-prod

  redis:
    networks:
      - teleforma-prod

  memcached:
    networks:
      - teleforma-prod


volumes:
    app:
    channels:
    postgres:
    redis:


networks:
  teleforma-prod:
    driver: bridge