version: '3'

services:
  app:
    build:
      context: .
      args:
        dev: 0
    command: /bin/sh /srv/app/wsgi.sh
    restart: unless-stopped
    env_file:
      - env/prod.env
    volumes:
      - /mnt/crfpa-videos:/mnt/crfpa-videos
      - /mnt/crfpa-scripts:/mnt/crfpa-scripts
    networks:
      - teleforma-prod
  
  channels:
    build:
      context: .
      args:
        dev: 0
    command: /bin/sh /srv/app/asgi.sh
    volumes:
      - ./app/:/srv/app
      - ./bin:/srv/bin
      - ./lib:/srv/lib
      - ./teleforma/:/srv/src/teleforma/teleforma
      - ./var/log/app:/var/log/app
    env_file:
      - env/prod.env
    networks:
      - teleforma-prod
    links:
      - db:db
      - redis
      - memcached
    depends_on:
      - db
      - redis
      - memcached

  db:
    env_file:
      - env/prod.env
    networks:
      - teleforma-prod

  redis:
    networks:
      - teleforma-prod

  memcached:
    networks:
      - teleforma-prod


volumes:
    app:
    channels:
    db:
    redis:


networks:
  teleforma-prod:
    driver: bridge
