version: '3'

services:
  app:
    build:
      context: .
      args:
        dev: 0
    command: /bin/sh /srv/app/wsgi.sh
    restart: unless-stopped
    env_file:
      - env/staging.env
    volumes:
      - /mnt/crfpa-videos:/mnt/crfpa-videos
      - /mnt/crfpa-scripts:/mnt/crfpa-scripts
    ports:
      - "9001:8000"
    networks:
      - teleforma-staging
  
  channels:
    build:
      context: .
      args:
        dev: 0
    command: /bin/sh /srv/app/asgi.sh
    volumes:
      - ./app/:/srv/app
      - ./bin:/srv/bin
      - ./lib:/srv/lib
      - ./teleforma/:/srv/src/teleforma/teleforma
      - ./var/log/app:/var/log/app
      - ./var/run/app:/var/run/app
    ports:
      - "9002:8000"
    links:
      - db
      - redis
    env_file:
      - env/staging.env
    networks:
      - teleforma-staging

  db:
    env_file:
      - env/staging.env
    networks:
      - teleforma-staging

  redis:
    networks:
      - teleforma-staging

  memcached:
    networks:
      - teleforma-staging

volumes:
    app:
    channels:
    db:
    redis:

networks:
  teleforma-staging:
    driver: bridge